services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - profilepro/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn profilepro.wsgi:application --bind 0.0.0.0:8000

volumes:
  static-data: