# Generated by Django 5.0.6 on 2024-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description', max_length=254, verbose_name='Description')),
                ('parameters', models.CharField(blank=True, default='', help_text='Parameters', max_length=254, verbose_name='Parameters')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
                'ordering': ('name',),
            },
        ),
    ]
