# Generated by Django 5.0.6 on 2024-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Name', max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', help_text='Description', max_length=254, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='', help_text='Image', upload_to='images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image Settings',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.TextField(blank=True, default='', help_text='Parameters', max_length=254, verbose_name='Parameters'),
        ),
    ]
