# Generated by Django 5.0.6 on 2024-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_imagesetting_alter_generalsetting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('skill', models.CharField(blank=True, default='', help_text='Skill', max_length=254, verbose_name='Skill')),
                ('description', models.CharField(blank=True, default='', help_text='Description', max_length=254, verbose_name='Description')),
                ('percentage', models.IntegerField(blank=True, default=0, help_text='Percentage', verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Skill Setting',
                'verbose_name_plural': 'Skill Settings',
                'ordering': ('skill',),
            },
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('name',), 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'ordering': ('name',), 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
