# Generated by Django 5.0.6 on 2024-07-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_skillsetting_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('company_name', models.CharField(blank=True, default='', help_text='Company Name', max_length=254, verbose_name='Company Name')),
                ('job_position', models.CharField(blank=True, default='', help_text='Job Position', max_length=254, verbose_name='Job Position')),
                ('job_location', models.CharField(blank=True, default='', help_text='Job Location', max_length=254, verbose_name='Job Location')),
                ('start_date', models.DateField(blank=True, help_text='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='End Date', verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Experience Setting',
                'verbose_name_plural': 'Experience Settings',
                'ordering': ('company_name',),
            },
        ),
    ]
