# Generated by Django 5.0.6 on 2024-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_experiencesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesetting',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='End Date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='experiencesetting',
            name='start_date',
            field=models.DateField(help_text='Start Date', verbose_name='Start Date'),
        ),
    ]
