# Generated by Django 5.0.6 on 2024-07-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_experiencesetting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencesetting',
            options={'ordering': ('start_date',), 'verbose_name': 'Experience Setting', 'verbose_name_plural': 'Experience Settings'},
        ),
    ]
