# Generated by Django 5.0.6 on 2024-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_experiencesetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('school_name', models.CharField(blank=True, default='', help_text='School Name', max_length=254, verbose_name='School Name')),
                ('major', models.CharField(blank=True, default='', help_text='Major', max_length=254, verbose_name='Major')),
                ('department', models.CharField(blank=True, default='', help_text='Department', max_length=254, verbose_name='Department')),
                ('start_date', models.DateField(help_text='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='End Date', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education Setting',
                'verbose_name_plural': 'Education Settings',
                'ordering': ('-start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='experiencesetting',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experience Setting', 'verbose_name_plural': 'Experience Settings'},
        ),
    ]
