# Generated by Django 5.0.6 on 2024-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_educationsetting_alter_experiencesetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Name', max_length=100, verbose_name='Name')),
                ('url', models.URLField(default='', help_text='Url', verbose_name='Url')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon', max_length=254, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media Setting',
                'verbose_name_plural': 'Social Media Settings',
                'ordering': ('name',),
            },
        ),
    ]
