# Generated by Django 5.0.6 on 2024-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_socialmediasetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.TextField(blank=True, default='', help_text='Parameters', verbose_name='Parameters'),
        ),
    ]
