# Generated by Django 5.0.6 on 2024-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_personalinformationsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformationsetting',
            options={'ordering': ('order',), 'verbose_name': 'Personal Information Setting', 'verbose_name_plural': 'Personal Information Settings'},
        ),
        migrations.AddField(
            model_name='personalinformationsetting',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Order', verbose_name='Order'),
        ),
    ]
