# Generated by Django 5.0.6 on 2024-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_personalinformationsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated Date', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date', verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Name', max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', help_text='Description', max_length=254, verbose_name='Description')),
                ('file', models.FileField(blank=True, default='', help_text='File', upload_to='files/', verbose_name='File')),
                ('button_text', models.CharField(blank=True, default='', help_text='Button Text', max_length=100, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'Upload Setting',
                'verbose_name_plural': 'Upload Settings',
                'ordering': ('name',),
            },
        ),
    ]
