# Generated by Django 5.0.6 on 2024-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_uploadsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadsetting',
            options={'ordering': ('slug',), 'verbose_name': 'Upload Setting', 'verbose_name_plural': 'Upload Settings'},
        ),
        migrations.RemoveField(
            model_name='uploadsetting',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadsetting',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug', max_length=100, verbose_name='Slug'),
        ),
    ]
